apiVersion: v2
name: kafka-db-forwarder
description: A Helm chart for Kafka to Database Forwarder

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
- name: common
  version: 0.1.0
  repository: file://../../common
