apiVersion: v2
name: cluster-ui
description: A Helm chart for the cluster-ui React frontend application

type: application

version: 0.1.0

appVersion: 1.0.0

dependencies:
- name: common
  version: 0.1.0
  repository: file://../../common 