apiVersion: v2
name: kafka
description: A Helm chart for Kafka and Schema Registry

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
- name: common
  version: "*"
  repository: "file://../../common"
