namespace: factory

replicaCount: 1

image:
  name: confluentinc/cp-schema-registry:7.3.2
  imagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8081

ingress:
  enabled: false

deployment:
  create: false

statefulset:
  create: true

resources: { }

autoscaling:
  enabled: false

nodeSelector: { }

tolerations: [ ]

affinity: { }

livenessProbe: { }

readinessProbe: { }

env:
  - name: SCHEMA_REGISTRY_HOST_NAME
    value: schema-registry
  - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
    value: 'PLAINTEXT://kafka-svc:9092'
  - name: SCHEMA_REGISTRY_LISTENERS
    value: http://0.0.0.0:8081