namespace: factory

replicaCount: 1

image:
  name: quay.io/keycloak/keycloak:legacy
  imagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

service:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
    - name: follower
      port: 2888
    - name: leader
      port: 3888
  clusterIP: None


ingress:
  enabled: false

deployment:
  create: false

statefulset:
  create: true

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }

livenessProbe: { }

readinessProbe: { }

postStartCommands:
  - "sh"
  - "-c"
  - >
    echo $(( $(cat /etc/hosts | grep zookeeper | awk '{print($3)}' | awk '{split($0,array,"-")} END{print array[3]}') + 1 )) > /bitnami/zookeeper/data/myid

configmap:
  values:
    DB_VENDOR: 'POSTGRES'
    DB_ADDR: 'postgres'
    DB_DATABASE: 'keycloak'
    DB_USER: 'keycloak'
    DB_SCHEMA: 'public'
    DB_PASSWORD: 'password'
    KEYCLOAK_USER: 'admin'
    KEYCLOAK_PASSWORD: 'Pa55w0rd'

env:
  - name: ALLOW_ANONYMOUS_LOGIN
    value: "yes"
  - name: ZOO_SERVERS
    value: zookeeper-cluster:2181:2888:3888