{{- define "common.clusterRole" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
  labels:
    app: {{ .Chart.Name }}
    {{- include "helm.labels" . | nindent 4 }}
rules:
  - apiGroups: {{ .Values.clusterRole.apiGroups }}
    resources: {{ .Values.clusterRole.resources }}
    verbs: {{ .Values.clusterRole.verbs }}
{{- end }}
