{{- define "common.clusterRoleBinding" -}}
{{- if hasKey .Values "clusterRoleBinding"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-crb
  labels:
    app: {{ .Chart.Name }}
    {{- include "helm.labels" . | nindent 4 }}
{{- if hasKey .Values.clusterRoleBinding "subjects"}}
subjects:
  {{- range $subject := .Values.clusterRoleBinding.subjects }}
  - kind: ServiceAccount
    name: {{ $subject }}
    namespace: {{ $.Values.namespace }}
  {{- end }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.clusterRoleBinding.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
