{{- define "common.rolebinding" -}}
{{- range $name, $binding := .Values.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $binding.roleName }}
subjects:
  {{- toYaml $binding.subjects | nindent 4 }}
{{- end }}
{{- end }} 