{{- define "common.role" -}}
{{- range $name, $role := .Values.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
rules:
    {{- toYaml $role.rules | nindent 4 }}
{{- end }}
{{- end }} 