{{- define "common.serviceaccount" -}}
{{- range $name, $service := .Values.serviceaccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
{{- end }}
{{- end }}