{{- define "common.configmap" -}}
{{- if hasKey .Values "configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
{{- range $key, $val := .Values.configmap.values }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
  {{- end}}