{{- define "common.persistentVolumeClaim" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "helm.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  accessModes: {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
  volumeName: {{ .Chart.Name }}-pv
{{- end }}
