{{- define "common.serviceAccount" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  {{- if hasKey .Values.serviceAccount "labels"}}
  labels:
    {{ .Values.serviceAccount.labels . | nindent 4 }}
  {{- end }}
  {{- if hasKey .Values.serviceAccount "annotations"}}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if hasKey .Values.serviceAccount "automountServiceAccountToken"}}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
  {{- end }}
  {{- end }}