namespace: factory

replicaCount: 1

image:
  name: juliantheking/front-service
  imagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30000

ingress:
  enabled: false

deployment:
  create: true

configmap:
  values:
    JWT_SECRET : $(echo -n "`aws ssm get-parameter --name /CICD/JWT_SECRET --with-decrypt --region=eu-central-1 --output text --query Parameter.Value`")

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe: {}

readinessProbe: {}

env:
  - name: JWT_SECRET
    valueFrom:
      configMapKeyRef:
        name: front-service-config
        key: JWT_SECRET