apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
data:
  '5432': factory/database-svc:5432
  '9092': factory/kafka-broker-1-service:19092
  '9093': factory/kafka-broker-2-service:19092
  '9094': factory/kafka-broker-3-service:19092
